/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gerencia;

import Db.DbMain;
import Funcoes.Dates;
import Funcoes.VariaveisGlobais;
import Funcoes.toPrint;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.export.JRPdfExporter;

/**
 *
 * @author supervisor
 */
public class jCaixa extends javax.swing.JInternalFrame {
    DbMain conn = VariaveisGlobais.con;
    Date cxdata = null;
    
    /**
     * Creates new form jCaixa
     */
    public jCaixa() {
        initComponents();
        
        try {
            cxdata = Dates.StringtoDate(conn.LerCamposTabela(new String[] {"data"}, "ncaixa", "f_cod = " + VariaveisGlobais.cdlogado)[0][3],"yyyy-MM-dd");
        } catch (Exception e) {}            
        jDTcx.setText(Dates.DateFormat("dd-MM-yyyy", cxdata == null ? new Date() : cxdata));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDN = new javax.swing.JFormattedTextField();
        jCH = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jCT = new javax.swing.JSpinner();
        jbtFechar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jDTcx = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle(".:: Fechamento do Caixa");
        setVisible(true);

        jLabel1.setText("Dinheiro:");

        jLabel2.setText("Cheque:");

        jDN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jDN.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jDN.setText("0,00");

        jCH.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jCH.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jCH.setText("0,00");

        jLabel3.setText("Cartão nº de Doctos:");

        jCT.setModel(new javax.swing.SpinnerNumberModel());

        jbtFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/aguardando.png"))); // NOI18N
        jbtFechar.setText("Fechar");
        jbtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtFecharActionPerformed(evt);
            }
        });

        jLabel4.setText("Dt.Caixa:");

        jDTcx.setEditable(false);
        jDTcx.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDTcx))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jCH))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDN))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCT, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jDTcx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtFechar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtFecharActionPerformed
        Map parametros = new HashMap();
        parametros.put("data", cxdata == null ? new Date() : cxdata);
        parametros.put("logado", Integer.valueOf(VariaveisGlobais.cdlogado));
        parametros.put("ap_cx_dn", new BigDecimal(jDN.getText().replace(".", "").replace(",", ".")));
        parametros.put("ap_cx_ch", new BigDecimal(jCH.getText().replace(".", "").replace(",", ".")));
        parametros.put("ap_cx_ct", Integer.valueOf(jCT.getValue().toString()));

        try {
            String fileName = "reports/nCaixas.jasper";
            JasperPrint print = JasperFillManager.fillReport(fileName, parametros, conn.conn);

            // Create a PDF exporter
            JRExporter exporter = new JRPdfExporter();

            // Configure the exporter (set output file name and print object)
            String outFileName = "reports/Fatura/Caixa_" + VariaveisGlobais.logado.trim().toUpperCase() + "_" + Dates.DateFormat("ddMMyyyyHHmmss", cxdata == null ? new Date() : cxdata) + ".pdf";
            exporter.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, outFileName);
            exporter.setParameter(JRExporterParameter.JASPER_PRINT, print);

            // Export the PDF file
            exporter.exportReport();
            
            boolean isprint = false;
            while (isprint == false) {
                new toPrint(outFileName, "NORMAL", "PDF", "INTERNA");
                isprint = JOptionPane.showConfirmDialog(this, "Imprimiu corretamente?", "Impressão", YES_NO_OPTION) == YES_OPTION ? true : false;
            }
            try {
                conn.ExecutarComando("DELETE FROM ncaixa WHERE f_cod = " + VariaveisGlobais.cdlogado + ";");
            } catch (Exception e) {}
            
        } catch (JRException e) {
            e.printStackTrace();
            System.exit(1);
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        }        
    }//GEN-LAST:event_jbtFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jCH;
    private javax.swing.JSpinner jCT;
    private javax.swing.JFormattedTextField jDN;
    private javax.swing.JTextField jDTcx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtFechar;
    // End of variables declaration//GEN-END:variables
}
