/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gerencia;

import Caixa.jPagRec;
import Db.DbMain;
import Funcoes.Dates;
import Funcoes.LerValor;
import static Funcoes.LerValor.String2Db;
import Funcoes.LimitedTextField;
import Funcoes.TableControl;
import Funcoes.VariaveisGlobais;
import java.awt.Point;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.regex.PatternSyntaxException;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import jclinica.jMenuPrincipal;

/**
 *
 * @author supervisor
 */
public class jDespesas extends javax.swing.JInternalFrame {
    DbMain conn = VariaveisGlobais.con;
    TableRowSorter<TableModel> sorter;

    /**
     * Creates new form jDespesas
     */
    public jDespesas() {
        initComponents();
        
        try {
            Date cxdata = Dates.StringtoDate(conn.LerCamposTabela(new String[] {"data"}, "ncaixa", "f_cod = " + VariaveisGlobais.cdlogado)[0][3],"yyyy-MM-dd");
            Date hoje = new Date();
            if (!Dates.DateFormat("dd-MM-yyyy", cxdata).equals(Dates.DateFormat("dd-MM-yyyy", new Date()))) {
                JOptionPane.showMessageDialog(null, "Caixa anterior não foi fechado!","Atenção",INFORMATION_MESSAGE);
                this.dispose();
            }
        } catch (Exception e) {}            
        
        FillGrupos(jGrupo);
        {
            jBuscar.addKeyListener(new KeyAdapter() {
                public void keyReleased(KeyEvent e) {
                    if ("".equals(jBuscar.getText().trim())) {
                        sorter.setRowFilter(null);
                    } else {
                        try {
                            sorter.setRowFilter(RowFilter.regexFilter(jBuscar.getText().trim()));
                            jAdc.setEnabled(jGrupo.getRowCount() <= 0);
                            jDel.setEnabled(false);
                        } catch (Exception ex) {}
                    }
                }

                public void keyTyped(KeyEvent e) {
                }

                public void keyPressed(KeyEvent e) {
                }
            });
            jBuscar.requestFocus();
        }
        jbtLancar.setEnabled(false);
        
    }

    private void FillGrupos(JTable tbl) {
        String tsql = "SELECT id, descricao FROM grupos ORDER BY id;";
        ResultSet trs = conn.AbrirTabela(tsql, ResultSet.CONCUR_READ_ONLY);
        String[][] aheader = { { "Id", "Descrição" }, { "0", "380" } };
        TableControl.header(tbl, aheader);
        TableControl.delall(tbl);
        
        String mid = null, mdesc = null;
        try {
            while (trs.next()) {
                try { mid = trs.getString("id"); } catch (SQLException e) {}
                try { mdesc = trs.getString("descricao"); } catch (SQLException e) {}
                TableControl.add(tbl, new String[][] { { mid, mdesc }, { "C", "L" } }, true);
                sorter = new TableRowSorter(tbl.getModel());
                tbl.setRowSorter(sorter);
            }
        } catch (SQLException e) {}
        try {trs.close();} catch (SQLException e) {}
        jAdc.setEnabled(false);
        jDel.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jGrupo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jBuscar = new LimitedTextField(100);
        jAdc = new javax.swing.JLabel();
        jDel = new javax.swing.JLabel();
        jClear = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDescricao = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jValor = new javax.swing.JFormattedTextField();
        jbtLancar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle(".:: Despesas");
        setVisible(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jGrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jGrupo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jGrupo.setShowVerticalLines(false);
        jGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jGrupoMouseReleased(evt);
            }
        });
        jGrupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jGrupoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jGrupo);
        if (jGrupo.getColumnModel().getColumnCount() > 0) {
            jGrupo.getColumnModel().getColumn(0).setResizable(false);
            jGrupo.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setBackground(new java.awt.Color(105, 109, 238));
        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText(" Grupos");
        jLabel1.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/find.png"))); // NOI18N

        jBuscar.setBackground(new java.awt.Color(254, 254, 254));
        jBuscar.setBorder(null);
        jBuscar.setMargin(new java.awt.Insets(0, 2, 0, 2));

        jAdc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAdc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ok.png"))); // NOI18N
        jAdc.setToolTipText("Adiciona Grupo...");
        jAdc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jAdcMouseReleased(evt);
            }
        });

        jDel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/cancel.png"))); // NOI18N
        jDel.setToolTipText("Deleta permanentemente Grupo...");
        jDel.setEnabled(false);
        jDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jDelMouseReleased(evt);
            }
        });

        jClear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/clear.png"))); // NOI18N
        jClear.setToolTipText("Limpa campo de busca...");
        jClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jClearMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jClear, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jAdc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jDel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jClear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAdc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel4.setBackground(new java.awt.Color(105, 109, 238));
        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText(" Descrição");
        jLabel4.setToolTipText("");
        jLabel4.setOpaque(true);

        jDescricao.setColumns(20);
        jDescricao.setLineWrap(true);
        jDescricao.setRows(5);
        jDescricao.setTabSize(4);
        jDescricao.setDoubleBuffered(true);
        jScrollPane2.setViewportView(jDescricao);

        jLabel5.setText("Valor:");

        jValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jValor.setText("0,00");
        jValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jValorFocusGained(evt);
            }
        });
        jValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jValorKeyReleased(evt);
            }
        });

        jbtLancar.setText("Lançar");
        jbtLancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLancarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jValor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtLancar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtLancar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jClearMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClearMouseReleased
        jGrupo.getSelectionModel().clearSelection();
        sorter.setRowFilter(null);
        jbtLancar.setEnabled(false);
        jBuscar.setText(null); 
        jBuscar.requestFocus(); 
        jAdc.setEnabled(false);
        jDel.setEnabled(false);
    }//GEN-LAST:event_jClearMouseReleased

    private void jGrupoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jGrupoKeyReleased
        int trow = jGrupo.getSelectedRow();
        int modelRow = jGrupo.convertRowIndexToModel(trow);
        String tid = jGrupo.getModel().getValueAt(modelRow, 0).toString();
        jAdc.setEnabled(false);
        jDel.setEnabled(true);
    }//GEN-LAST:event_jGrupoKeyReleased

    private void jGrupoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGrupoMouseReleased
        if (evt.getClickCount() == 2) {
            Point p = evt.getPoint();
            int row = jGrupo.rowAtPoint(p);
            int trow = jGrupo.getSelectedRow();
            int modelRow = jGrupo.convertRowIndexToModel(trow);
            String tgr = jGrupo.getModel().getValueAt(modelRow, 1).toString();
            ExtornaDesp(tgr);
        }
        jAdc.setEnabled(false);
        jDel.setEnabled(true);
    }//GEN-LAST:event_jGrupoMouseReleased

    private void ExtornaDesp(String grupo) {
        String tsql = "SELECT d.id, d.descricao, d.valor, d.naut FROM ndespesas d, ncaixa c " + 
                      "WHERE (d.naut = c.autenticacao) and grupo = '%s' and data = '%s' and " + 
                      "oper = 'DES' and logado = '%s' ORDER BY d.id;";
        tsql = String.format(tsql, 
                grupo,
                Dates.DateFormat("yyyy-MM-dd", new Date()),
                VariaveisGlobais.logado
        );
        ResultSet trs = conn.AbrirTabela(tsql, ResultSet.CONCUR_READ_ONLY);
        final JTable tbl = new JTable();
        tbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                JTable table =(JTable) me.getSource();
                Point p = me.getPoint();
                int row = table.rowAtPoint(p);
                if (me.getClickCount() == 2) {
                    int trow = tbl.getSelectedRow();
                    int modelRow = tbl.convertRowIndexToModel(trow);
                    String tficha = tbl.getModel().getValueAt(modelRow, 0).toString();
                    //BuscarMedico(tficha);
                }
            }
        });
        
        String[][] aheader = { { "id", "Descrição", "Valor", "naut" }, { "60", "380", "150", "0" } };
        TableControl.header(tbl, aheader);
        TableControl.delall(tbl);
        
        String mid = null, mdesc = null, mvalor = null, maut = null;
        try {
            while (trs.next()) {
                try { mid = trs.getString("id"); } catch (SQLException e) {}
                try { mdesc = trs.getString("descricao"); } catch (SQLException e) {}
                try { mvalor = LerValor.floatToCurrency(Float.valueOf(trs.getBigDecimal("valor").toString()),2); } catch (SQLException e) {}
                try { maut = trs.getString("naut"); } catch (SQLException e) {}
                TableControl.add(tbl, new String[][] { { mid, mdesc, mvalor, maut }, { "C", "L", "R", "C" } }, true);
                sorter = new TableRowSorter(tbl.getModel());
                tbl.setRowSorter(sorter);
            }
        } catch (SQLException e) {}
        try {trs.close();} catch (SQLException e) {}
        tbl.setSize(300,200);
        
        JScrollPane jScrollPane1 = new JScrollPane();
        jScrollPane1.setViewportView(tbl);
        jLabel1 = new JLabel();
        jLabel1.setText("Buscar:");
        final JTextField jbuscar = new JTextField();
        jbuscar.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                if ("".equals(jbuscar.getText().trim())) {
                    sorter.setRowFilter(null);
                } else {
                    try {
                        sorter.setRowFilter(
                               RowFilter.regexFilter(jbuscar.getText().trim()));
                    } catch (PatternSyntaxException pse) {
                       System.err.println("Bad regex pattern");
                    }
                }
            }

            public void keyTyped(KeyEvent e) {
            }

            public void keyPressed(KeyEvent e) {
            }
        });
        jbuscar.requestFocus();
        
        JPanel panel = new JPanel();
        GroupLayout layout = new GroupLayout(panel);
        //getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 275, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jbuscar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel.setLayout(layout);
        Object[] options = { "Ok", "Cancelar" };
        int opc = JOptionPane.showOptionDialog(this, panel,"Extornar despesa do dia.",JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null,options, options[0]);
        if (opc == JOptionPane.YES_OPTION) {
            int trow = tbl.getSelectedRow();
            if (trow > -1) {
                int modelRow = tbl.convertRowIndexToModel(trow);
                String tid = tbl.getModel().getValueAt(modelRow, 0).toString();
                String taut = tbl.getModel().getValueAt(modelRow, 3).toString();
                String sql = "DELETE FROM ndespesas WHERE id = '%s';";
                sql = String.format(sql, tid);
                try {
                    conn.ExecutarComando(sql);
                    sql = "UPDATE ncaixa SET oper = Trim(oper) || 'X' WHERE autenticacao = '%s';";
                    sql = String.format(sql, taut);
                    conn.ExecutarComando(sql);
                } catch (Exception e) {}
            }
        }
    }
    
    private void jAdcMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAdcMouseReleased
        int opc = JOptionPane.showConfirmDialog(this, "Lançar \"" + jBuscar.getText().trim() + "\" na tabela de grupos?","Lançamento",YES_NO_OPTION);
        if ( opc == YES_OPTION) {
            String sql = "INSERT INTO grupos(descricao) VALUES ('%s');";
            sql = String.format(sql, jBuscar.getText());
            try {
                conn.ExecutarComando(sql); 
                FillGrupos(jGrupo);
            } catch (Exception e) {}
        }
    }//GEN-LAST:event_jAdcMouseReleased

    private void jValorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jValorFocusGained
        jbtLancar.setEnabled(false);
    }//GEN-LAST:event_jValorFocusGained

    private void jValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jValorKeyReleased
        jbtLancar.setEnabled(LerValor.StringToFloat(jValor.getText()) > 0 && jDescricao.getText().trim().length() > 0 && jGrupo.getSelectedRowCount() > 0);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER ) {
            jbtLancar.requestFocus();
        }
    }//GEN-LAST:event_jValorKeyReleased

    private void jDelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDelMouseReleased
        int opc = JOptionPane.showConfirmDialog(this, "Exclui o grupo \"" + jGrupo.getModel().getValueAt(jGrupo.getSelectedRow(),1).toString() + "\"?","Exclusão",YES_NO_OPTION);
        if (opc == YES_OPTION) {
            String tsql = "DELETE FROM grupos WHERE id = '%s';";
            tsql = String.format(tsql,jGrupo.getModel().getValueAt(jGrupo.getSelectedRow(),0).toString());
            try {
                conn.ExecutarComando(tsql);
            } catch (Exception e) {}
            
            int opc2 = JOptionPane.showConfirmDialog(this, "Exclui os lançamentos anteriosres do grupo \"" + jGrupo.getModel().getValueAt(jGrupo.getSelectedRow(),1).toString() + "\"?","Exclusão",YES_NO_OPTION);
            if (opc2 == YES_OPTION) {
                tsql = "DELETE FROM ndespesas WHERE Upper(grupo) LIKE '%" + jGrupo.getModel().getValueAt(jGrupo.getSelectedRow(),1).toString() + "';";
                try {
                    conn.ExecutarComando(tsql);
                } catch (Exception e) {}
            }
            FillGrupos(jGrupo);
        }
    }//GEN-LAST:event_jDelMouseReleased

    private void jbtLancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLancarActionPerformed
        jPagRec tpg = new jPagRec(null, true);
        tpg.setValor(jValor.getText());
        tpg.setVisible(true);
        Object[] retorno = tpg.getPagRec();
        tpg = null;
        String[] tipopag = new String[] {"ND","DN","CH","CT"};
        if (Integer.valueOf(retorno[0].toString()) == 0) return;
        java.sql.Date datap = Dates.toSqlDate(Dates.StringtoDate((String)((Object[])retorno[2])[3],"dd-MM-yyyy"));
        String pbanco = (String)((Object[])retorno[2])[0];
        String pagencia = (String)((Object[])retorno[2])[1];
        String pncheque = (String)((Object[])retorno[2])[2];
        String pnrcartao = (String)retorno[1];
        int aut = conn.LancarCaixa(
                "DEB",
                tipopag[Integer.valueOf(retorno[0].toString())],
                "DES",
                0,
                datap, 
                pbanco,
                pagencia,
                pncheque,
                pnrcartao,
                new BigDecimal(String2Db(jValor.getText()).replace(",", ".")),
                Integer.valueOf(VariaveisGlobais.cdlogado)
        );
        if (aut == 0) return;
        String tsql = "INSERT INTO ndespesas(grupo, descricao, valor, tiporec, bco, agencia, ncheque, datap, naut, logado)" +
                      " VALUES ('%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s');";
        tsql = String.format(tsql, 
                jGrupo.getModel().getValueAt(jGrupo.getSelectedRow(),1).toString(),
                jDescricao.getText(),
                new BigDecimal(String2Db(jValor.getText()).replace(",", ".")),
                tipopag[Integer.valueOf(retorno[0].toString())],
                pbanco,
                pagencia,
                pncheque,
                datap,
                aut, 
                VariaveisGlobais.logado
        );
        System.out.println(tsql);
        try {
            conn.ExecutarComando(tsql);
            jGrupo.getSelectionModel().clearSelection();
            jBuscar.setText(null);
            sorter.setRowFilter(null);
            jDescricao.setText(null);
            jValor.setText("0,00");
            jbtLancar.setEnabled(false);
            jBuscar.setText(null); 
            jBuscar.requestFocus(); 
            jAdc.setEnabled(false);
            jDel.setEnabled(false);
        } catch (Exception e) {}
    }//GEN-LAST:event_jbtLancarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAdc;
    private javax.swing.JTextField jBuscar;
    private javax.swing.JLabel jClear;
    private javax.swing.JLabel jDel;
    private javax.swing.JTextArea jDescricao;
    private javax.swing.JTable jGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFormattedTextField jValor;
    private javax.swing.JButton jbtLancar;
    // End of variables declaration//GEN-END:variables
}
