/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gerencia;

import Db.DbMain;
import Funcoes.Dates;
import Funcoes.LerValor;
import static Funcoes.LerValor.String2Db;
import Funcoes.VariaveisGlobais;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.util.Date;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author supervisor
 */
public class jPasCaixa extends javax.swing.JInternalFrame {
    DbMain conn = VariaveisGlobais.con;
    
    /**
     * Creates new form jPasCaixa
     */
    public jPasCaixa() {
        initComponents();

        try {
            Date cxdata = Dates.StringtoDate(conn.LerCamposTabela(new String[] {"data"}, "ncaixa", "f_cod = " + VariaveisGlobais.cdlogado)[0][3],"yyyy-MM-dd");
            Date hoje = new Date();
            if (!Dates.DateFormat("dd-MM-yyyy", cxdata).equals(Dates.DateFormat("dd-MM-yyyy", new Date()))) {
                JOptionPane.showMessageDialog(null, "Caixa anterior não foi fechado!","Atenção",INFORMATION_MESSAGE);
                this.dispose();
            }
        } catch (Exception e) {}            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jValor = new javax.swing.JFormattedTextField();
        jbtLancar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jETA = new javax.swing.JRadioButton();
        jETD = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setTitle(".:: Lançamento Caixa");
        setVisible(true);

        jLabel1.setText("Valor:");

        jValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jValor.setText("0,00");
        jValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jValorKeyReleased(evt);
            }
        });

        jbtLancar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/encerrado.png"))); // NOI18N
        jbtLancar.setText("Lançar");
        jbtLancar.setEnabled(false);
        jbtLancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLancarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        buttonGroup1.add(jETA);
        jETA.setText("Saida");
        jETA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jETAActionPerformed(evt);
            }
        });

        buttonGroup1.add(jETD);
        jETD.setSelected(true);
        jETD.setText("Entrada");
        jETD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jETDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jETD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jETA)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jETD)
                    .addComponent(jETA))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jValor, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtLancar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtLancar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jETAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jETAActionPerformed
        jValor.setText("0,00");
        jValor.requestFocus();
    }//GEN-LAST:event_jETAActionPerformed

    private void jETDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jETDActionPerformed
        jValor.setText("0,00");
        jValor.requestFocus();
    }//GEN-LAST:event_jETDActionPerformed

    private void jValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jValorKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (LerValor.db2Float(jValor.getText()) > 0) {
                jbtLancar.setEnabled(true);
                jbtLancar.requestFocus();
            }
        }
    }//GEN-LAST:event_jValorKeyReleased

    private void jbtLancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLancarActionPerformed
        int aut = conn.LancarCaixa(
                jETD.isSelected() ? "CRE" : "DEB",
                "DN",
                "PCX",
                0,
                new Date(), 
                null,
                null,
                null,
                null,
                new BigDecimal(String2Db(jValor.getText()).replace(",", ".")),
                Integer.valueOf(VariaveisGlobais.cdlogado)
        );
        if (aut == 0) return;
        JOptionPane.showInternalMessageDialog(this, "Lançamento Ok!");
        jValor.setText("0,00");
        jbtLancar.setEnabled(false);
        jETD.requestFocus();
    }//GEN-LAST:event_jbtLancarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jETA;
    private javax.swing.JRadioButton jETD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JFormattedTextField jValor;
    private javax.swing.JButton jbtLancar;
    // End of variables declaration//GEN-END:variables
}
