/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jLogin.java
 *
 * Created on 02/02/2012, 10:21:22
 */
package Login;

import Db.DbMain;
import Funcoes.BackGroundDeskTopPane;
import Funcoes.Dates;
import Funcoes.VariaveisGlobais;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.ImageIcon;
import jclinica.jMenuPrincipal;

/**
 *
 * @author supervisor
 */
public class jLogin extends javax.swing.JDialog {
    DbMain conn = null;
    
    /** Creates new form jLogin */
    public jLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // background
        ImageIcon icone = new ImageIcon("login_cs.jpg");
        setIconImage(icone.getImage());
     
        setLocationRelativeTo(null);

        // Unidades de acesso remoto
        jUnidade.addItem(VariaveisGlobais.unidade);
        if (!"".equals(VariaveisGlobais.remoto1)) {
            jUnidade.addItem(VariaveisGlobais.remoto1);
        }
        if (!"".equals(VariaveisGlobais.remoto2)) {
            jUnidade.addItem(VariaveisGlobais.remoto2);
        }
        if (!"".equals(VariaveisGlobais.remoto3)) {
            jUnidade.addItem(VariaveisGlobais.remoto3);
        }
        if (!"".equals(VariaveisGlobais.remoto4)) {
            jUnidade.addItem(VariaveisGlobais.remoto4);
        }
        if (!"".equals(VariaveisGlobais.remoto5)) {
            jUnidade.addItem(VariaveisGlobais.remoto5);
        }
        jUnidade.addItem("");

        StartLogin();
                
    }

    private void StartLogin() {
        jUnidade.setVisible(true);
        jUnidade.setEnabled(true);
        jUsuario.setText("");
        jUsuario.setEnabled(false);
        jSenha.setText("");
        jSenha.setEnabled(false);
        
        jStatus.setVisible(false);
        jUnidade.requestFocus();        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new BackGroundDeskTopPane("/Figuras/login_cm.jpg");
        jUnidade = new javax.swing.JComboBox();
        jUsuario = new javax.swing.JTextField();
        jSenha = new javax.swing.JPasswordField();
        jStatus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".:: jClinica - Gestão de Clinicas");
        setAlwaysOnTop(true);
        setModal(true);
        setUndecorated(true);
        setResizable(false);

        jUnidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jUnidadeKeyPressed(evt);
            }
        });
        jDesktopPane1.add(jUnidade);
        jUnidade.setBounds(70, 142, 150, 20);

        jUsuario.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jUsuarioKeyPressed(evt);
            }
        });
        jDesktopPane1.add(jUsuario);
        jUsuario.setBounds(70, 170, 150, 25);

        jSenha.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jSenha.setForeground(new java.awt.Color(0, 0, 204));
        jSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSenhaKeyPressed(evt);
            }
        });
        jDesktopPane1.add(jSenha);
        jSenha.setBounds(70, 195, 150, 25);

        jStatus.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jStatus.setForeground(new java.awt.Color(255, 0, 0));
        jDesktopPane1.add(jStatus);
        jStatus.setBounds(70, 220, 300, 22);

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ATENÇÃO COM A DATA/HORA!!!");
        jLabel1.setOpaque(true);
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(180, 240, 220, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUnidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUnidadeKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) { 
            VariaveisGlobais.unidade = jUnidade.getModel().getSelectedItem().toString();
            conn = new DbMain(jUnidade.getModel().getSelectedItem().toString(),"postgres","7kf51b",VariaveisGlobais.dbnome);
            if (conn.conn != null) {
                jStatus.setText("");
                jUsuario.setText("");
                jSenha.setText("");
                jUsuario.setEnabled(true);
                jSenha.setEnabled(true);
                
                jStatus.setVisible(false);
                jUsuario.requestFocus();
            } else {
                jStatus.setText("Unidade não encontrada ou fora do ar!!!");
                jStatus.setVisible(true);
            }
        }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) { 
            this.dispose();
            System.exit(0);
        }        
    }//GEN-LAST:event_jUnidadeKeyPressed

    private void jUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUsuarioKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) { 
            jSenha.setText("");
            jSenha.requestFocus();
        }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) { 
            this.dispose();
            System.exit(0);
        }        
    }//GEN-LAST:event_jUsuarioKeyPressed

    private void jSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSenhaKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) { 
            // Aqui checa se o usuario é valido
            try {
                String mfuncao = "", mnome = "", mcpf = "";
                ResultSet rs = conn.AbrirTabela("SELECT usuario, senha, f_funcao, f_nome, f_cpf, f_cod FROM cadfun WHERE usuario = '" + jUsuario.getText().trim() + "' AND senha = '" + jSenha.getText().trim() + "';", WIDTH);
                if (rs.next()) {
                    jStatus.setText("");
                    mfuncao = rs.getString("f_funcao");
                    mnome = rs.getString("f_nome");
                    mcpf = rs.getString("f_cpf");
                    VariaveisGlobais.cdlogado = rs.getString("f_cod");
                } else {
                    jStatus.setText("Usuário ou Senha invalido!!!");
                    jUsuario.setText("");
                    jSenha.setText("");
                    jUsuario.requestFocus();
                    VariaveisGlobais.cdlogado = "";
                    return;
                }
                
                DbMain.FecharTabela(rs);
                this.dispose();

                // Quando o usuario for medico
                if (mfuncao.toLowerCase().contains("medico")) {
                    String[][] dados_medico = conn.LerCamposTabela(new String[] {"md_codigo"}, "medicos", "md_cpf = '" + mcpf + "'");
                    VariaveisGlobais.cdmedico = dados_medico[0][3].trim();
                    VariaveisGlobais.emedico = true;
                    VariaveisGlobais.nmmedico = mnome.trim();
                    VariaveisGlobais.lgmedico = jUsuario.getText().trim();
                } else {
                    VariaveisGlobais.cdmedico = "";
                    VariaveisGlobais.emedico = false;
                    VariaveisGlobais.nmmedico = "";
                    VariaveisGlobais.lgmedico = "";                    
                }
                
                // Saida automatica de pacientes
                String insertSQL = "insert into faturar select * from marcar where ma_data < '" + Dates.DateFormat("yyyy-MM-dd", new Date()) + "' AND ma_status > 0;";
                conn.ExecutarComando(insertSQL);
                String deleteSQL = "delete from marcar where ma_data < '" + Dates.DateFormat("yyyy-MM-dd", new Date()) + "' AND ma_status > 0;";
                conn.ExecutarComando(deleteSQL);
                
                VariaveisGlobais.logado = jUsuario.getText().toLowerCase().trim();
                jMenuPrincipal.main(new String[] {""});
            } catch (Exception e) {e.printStackTrace();}
            
//            try {
//                Date cxdata = Dates.StringtoDate(conn.LerCamposTabela(new String[] {"data"}, "ncaixa", "f_cod = " + VariaveisGlobais.cdlogado)[0][3],"yyyy-MM-dd");
//                System.out.println(cxdata);
//                Date hoje = new Date();
//                if (Dates.DateFormat("dd-MM-yyyy", cxdata) != Dates.DateFormat("dd-MM-yyyy", new Date())) {
//                    JOptionPane.showMessageDialog(null, "Caixa anterior não foi fechado!","Atenção",INFORMATION_MESSAGE);
//                    System.exit(0);
//                }
//            } catch (Exception e) {e.printStackTrace();}            
        }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) { 
            this.dispose();
            System.exit(0);
        }        
    }//GEN-LAST:event_jSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                jLogin dialog = new jLogin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jSenha;
    private javax.swing.JTextField jStatus;
    private javax.swing.JComboBox jUnidade;
    private javax.swing.JTextField jUsuario;
    // End of variables declaration//GEN-END:variables
}
