/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Caixa;

import Db.DbMain;
import Funcoes.Dates;
import Funcoes.FuncoesGlobais;
import Funcoes.LerValor;
import Funcoes.LimitedTextField;
import Funcoes.VariaveisGlobais;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.JTextField;

/**
 *
 * @author supervisor
 */
public class jPagRec extends javax.swing.JDialog {
    DbMain conn = VariaveisGlobais.con;
    int tipo = 0;
    String CT_numero = "";
    String CH_banco = "";
    String CH_agencia = "";
    String CH_numero = "";
    String CH_data = "";
    Object VR = "";
    
    /**
     * Creates new form jPagRec
     */
    public jPagRec(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        // DataChooserTextField
        {
            jCH_data.getDateEditor().getUiComponent().addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent evt) {
                    jbtLancar.setEnabled(LerValor.StringToFloat(jVR.getText()) >= LerValor.StringToFloat(jOP.getText()));
                    if (evt.getKeyCode() == KeyEvent.VK_ENTER && Dates.DiffDate(jCH_data.getDate(),new Date()) >= 0) {
                        jbtLancar.requestFocus();
                    }
                }
            });
            jCH_data.getDateEditor().getUiComponent().addFocusListener(new FocusAdapter() {
                @Override
                public void focusLost(FocusEvent evt) {
                    if (Dates.DiffDate(jCH_data.getDate(),new Date()) < 0) {
                        jCH_data.getDateEditor().getUiComponent().requestFocus();
                    }
                };
            });
        }
        
        // ComboBox
        {
            JTextField editor = (JTextField)jCH_banco.getEditor().getEditorComponent();
            editor.setHorizontalAlignment(JTextField.CENTER);
            editor.addKeyListener( new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent evt) {
                    if (evt.getKeyCode() == KeyEvent.VK_ENTER && !jCH_banco.getEditor().getItem().toString().trim().equalsIgnoreCase("")) {
                        jCH_agencia.requestFocus();
                    }
                }
            });
            jCH_banco.getEditor().getEditorComponent().addFocusListener( new FocusAdapter() {
                @Override
                public void focusLost(FocusEvent evt) {
                    if (jCH_banco.getSelectedIndex() == -1 && !((JTextField)jCH_banco.getEditor().getEditorComponent()).getText().trim().equals("")) {
                        jCH_banco.addItem(FuncoesGlobais.StrZero(jCH_banco.getEditor().getItem().toString().trim(),3));
                        String sql = "INSERT INTO bancos(banco) VALUES ('%s');";
                        sql = String.format(sql, FuncoesGlobais.StrZero(jCH_banco.getSelectedItem().toString().trim(),3));
                        conn.ExecutarComando(sql);
                    }
                }
            });
        }
        
        Selecao(0); // Tudo Habilitado
        fillBancos(jCH_banco);
        
    }

    public void setValor(String valor) {
        jOP.setText(valor); 
    }
    
    private void fillBancos(JComboBox box) {
        String sql = "select banco from bancos order by banco;";
        ResultSet crs = conn.AbrirTabela(sql, ResultSet.CONCUR_READ_ONLY);
        try {
            while (crs.next()) {
                box.addItem(crs.getString("banco"));
            }
        } catch (Exception e) {}
        DbMain.FecharTabela(crs);
        
        box.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jOP = new javax.swing.JFormattedTextField();
        jPanel7 = new javax.swing.JPanel();
        jCT = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCT_numero = new LimitedTextField(16);
        jLabel3 = new javax.swing.JLabel();
        jCH_data = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/#####", '_');
        jLabel4 = new javax.swing.JLabel();
        jCH_banco = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jCH_agencia = new LimitedTextField(6);
        jLabel6 = new javax.swing.JLabel();
        jCH_numero = new LimitedTextField(10);
        jLabel7 = new javax.swing.JLabel();
        jTR = new javax.swing.JTextField();
        jTRlabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jbtLancar = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jVR = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jDN = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jCH = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".:: Caixa");
        setAlwaysOnTop(true);
        setModal(true);
        setUndecorated(true);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(249, 18, 18));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBackground(new java.awt.Color(238, 254, 26));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Noto Serif", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 55, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CAIXA");

        jLabel9.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(9, 136, 0));
        jLabel9.setText("Valor da Operação:");

        jOP.setEditable(false);
        jOP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jOP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jOP.setText("0,00");
        jOP.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jOP, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jOP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel7.setPreferredSize(new java.awt.Dimension(104, 68));

        jCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ct.png"))); // NOI18N
        jCT.setToolTipText("Cartão");
        jCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCTMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jCT, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(55, 208, 184));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Cartão:");

        jCT_numero.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jCT_numero.setForeground(new java.awt.Color(15, 113, 118));
        jCT_numero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jCT_numero.setToolTipText("Entre aqui o número do cartão de crédito");
        jCT_numero.setEnabled(false);
        jCT_numero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCT_numeroFocusLost(evt);
            }
        });
        jCT_numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCT_numeroKeyReleased(evt);
            }
        });

        jLabel3.setText("Data:");

        jCH_data.setToolTipText("Entre aqui a data do cheque");
        jCH_data.setDate(new java.util.Date(-2208977612000L));
        jCH_data.setEnabled(false);

        jLabel4.setText("Banco:");

        jCH_banco.setEditable(true);
        jCH_banco.setToolTipText("Entre aqui o número do banco");
        jCH_banco.setEnabled(false);

        jLabel5.setText("Agência:");

        jCH_agencia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jCH_agencia.setText("000000");
        jCH_agencia.setToolTipText("Entre aqui o número da agência");
        jCH_agencia.setEnabled(false);
        jCH_agencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCH_agenciaFocusLost(evt);
            }
        });
        jCH_agencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCH_agenciaKeyReleased(evt);
            }
        });

        jLabel6.setText("Cheque Nº:");

        jCH_numero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jCH_numero.setText("0000000000");
        jCH_numero.setToolTipText("Entre aqui o número do cheque");
        jCH_numero.setEnabled(false);
        jCH_numero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCH_numeroFocusLost(evt);
            }
        });
        jCH_numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCH_numeroKeyReleased(evt);
            }
        });

        jLabel7.setText("Valor:");

        jTR.setEditable(false);
        jTR.setBackground(new java.awt.Color(36, 189, 46));
        jTR.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jTR.setForeground(new java.awt.Color(37, 2, 188));
        jTR.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTR.setText("0,00");
        jTR.setToolTipText("Troco a Receber");

        jTRlabel.setText("Troco:");

        jPanel6.setBackground(new java.awt.Color(60, 170, 171));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jbtLancar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ok.png"))); // NOI18N
        jbtLancar.setText("Lançar");
        jbtLancar.setEnabled(false);
        jbtLancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLancarActionPerformed(evt);
            }
        });

        jbtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/cancel.png"))); // NOI18N
        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtLancar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtCancelar)
                    .addComponent(jbtLancar))
                .addContainerGap())
        );

        jVR.setForeground(new java.awt.Color(23, 107, 4));
        jVR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jVR.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jVR.setText("0,00");
        jVR.setEnabled(false);
        jVR.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jVR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jVRFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jVRFocusLost(evt);
            }
        });
        jVR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jVRKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCT_numero))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCH_banco, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCH_agencia))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCH_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jVR)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(7, 7, 7)
                                .addComponent(jCH_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTRlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTR, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCT_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCH_banco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jCH_agencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jCH_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCH_data, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTRlabel)
                    .addComponent(jVR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(104, 68));

        jDN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/dn.png"))); // NOI18N
        jDN.setToolTipText("Dinheiro");
        jDN.setPreferredSize(new java.awt.Dimension(104, 68));
        jDN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jDNMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDN, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jDN, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel8.setPreferredSize(new java.awt.Dimension(104, 68));

        jCH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ch.png"))); // NOI18N
        jCH.setToolTipText("Cheque");
        jCH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCHMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jCH, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtLancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLancarActionPerformed
        this.CT_numero = jCT_numero.getText();
        try {this.CH_banco = jCH_banco.getSelectedItem().toString();} catch (NullPointerException e) {this.CH_banco = "";}
        this.CH_agencia = jCH_agencia.getText();
        this.CH_numero = jCH_numero.getText();
        this.CH_data = Dates.DateFormat("dd/MM/yyyy",jCH_data.getDate());
        this.VR = jOP.getValue();
        dispose();
    }//GEN-LAST:event_jbtLancarActionPerformed

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        if (this.tipo <= 0) dispose();
        if (this.tipo > 0) {
            Selecao(0);
        }
    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void jDNMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDNMouseReleased
        Selecao(1);
    }//GEN-LAST:event_jDNMouseReleased

    private void jCHMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCHMouseReleased
        Selecao(2);
    }//GEN-LAST:event_jCHMouseReleased

    private void jCTMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCTMouseReleased
        Selecao(3);
    }//GEN-LAST:event_jCTMouseReleased

    private void jCT_numeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCT_numeroKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !jCT_numero.getText().trim().equalsIgnoreCase("")) {
            if (this.tipo == 3) {
                jbtLancar.requestFocus();
            }
        }
    }//GEN-LAST:event_jCT_numeroKeyReleased

    private void jCH_agenciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCH_agenciaKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !jCH_agencia.getText().trim().isEmpty()) {
            jCH_numero.requestFocus();
        }
    }//GEN-LAST:event_jCH_agenciaKeyReleased

    private void jCH_numeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCH_numeroKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !jCH_numero.getText().trim().isEmpty()) {
            jCH_data.getDateEditor().getUiComponent().requestFocus();
        }
    }//GEN-LAST:event_jCH_numeroKeyReleased

    private void jCT_numeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCT_numeroFocusLost
        String ct = jCT_numero.getText().trim();
        ct = FuncoesGlobais.StrZero(ct, 16);
        jCT_numero.setText(ct);
        jbtLancar.setEnabled(LerValor.StringToFloat(jVR.getText()) >= LerValor.StringToFloat(jOP.getText()));
        jbtLancar.requestFocus();
    }//GEN-LAST:event_jCT_numeroFocusLost

    private void jCH_agenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCH_agenciaFocusLost
        jCH_agencia.setText(FuncoesGlobais.StrZero(jCH_agencia.getText().trim(),6));
    }//GEN-LAST:event_jCH_agenciaFocusLost

    private void jCH_numeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCH_numeroFocusLost
        jCH_numero.setText(FuncoesGlobais.StrZero(jCH_numero.getText().trim(),10));
    }//GEN-LAST:event_jCH_numeroFocusLost

    private void jVRFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jVRFocusGained
        ((JTextField)evt.getComponent()).selectAll();
    }//GEN-LAST:event_jVRFocusGained

    private void jVRFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jVRFocusLost
        try {
            jbtLancar.setEnabled(LerValor.StringToFloat(jVR.getText()) >= LerValor.StringToFloat(jOP.getText()));
            jTR.setText(LerValor.floatToCurrency(LerValor.StringToFloat(jVR.getText()) - LerValor.StringToFloat(jOP.getText()),2));
            if (LerValor.StringToFloat(jVR.getText()) - LerValor.StringToFloat(jOP.getText()) >= 0) {
                jTR.setForeground(Color.blue);
                jTRlabel.setText("Troco:");
            } else {
                jTR.setForeground(Color.red);
                jTRlabel.setText("Falta:");
                JOptionPane.showMessageDialog(this, "Valor digitado a menor!","Erro",ERROR_MESSAGE);
                jVR.requestFocus();
            }
        } catch (NullPointerException e) {jbtLancar.setEnabled(false);}
    }//GEN-LAST:event_jVRFocusLost

    private void jVRKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jVRKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && LerValor.db2Float(jVR.getText()) > 0) {
            jbtLancar.requestFocus();
        }
    }//GEN-LAST:event_jVRKeyReleased

    private void Selecao(int tipo) {
        if (tipo == 0) {
            // Habilitados
            jDN.setEnabled(true);
            jCH.setEnabled(true);
            jCT.setEnabled(true);

            jCT_numero.setText(null); jCT_numero.setEnabled(false);
            jCH_banco.setSelectedIndex(-1); jCH_banco.setEnabled(false);
            jCH_agencia.setText(null); jCH_agencia.setEnabled(false);
            jCH_numero.setText(null); jCH_numero.setEnabled(false);
            jCH_data.setDate(new Date()); jCH_data.setEnabled(false);
            jVR.setText("0,00"); jVR.setEnabled(false); jVR.setValue(0);
            jTR.setText("0,00"); jTR.setForeground(Color.black); 
            jTR.setVisible(true); jTRlabel.setVisible(true);
            
            jbtLancar.setEnabled(false);
            this.tipo = 0;
        } else if (tipo == 1) {
            // Dinheiro
            jDN.setEnabled(true);
            jCH.setEnabled(false);
            jCT.setEnabled(false);
            
            jCT_numero.setText(null); jCT_numero.setEnabled(false);
            jCH_banco.setSelectedIndex(-1); jCH_banco.setEnabled(false);
            jCH_agencia.setText(null); jCH_agencia.setEnabled(false);
            jCH_numero.setText(null); jCH_numero.setEnabled(false);
            jCH_data.setDate(new Date()); jCH_data.setEnabled(false);
            jVR.setText("0,00"); jVR.setEnabled(true); 
            jVR.setValue(0); jVR.setEditable(true); 
            jTR.setText("0,00"); jTR.setForeground(Color.black); 
            jTR.setVisible(true); jTRlabel.setVisible(true);
            jVR.requestFocus();
            
            jbtLancar.setEnabled(false);
            this.tipo = 1;
        } else if (tipo == 2) {
            // Cheque
            jDN.setEnabled(false);
            jCH.setEnabled(true);
            jCT.setEnabled(false);

            jCT_numero.setText(null); jCT_numero.setEnabled(false);
            jCH_banco.setSelectedIndex(-1); jCH_banco.setEnabled(true);
            jCH_agencia.setText(null); jCH_agencia.setEnabled(true);
            jCH_numero.setText(null); jCH_numero.setEnabled(true);
            jCH_data.setDate(new Date()); jCH_data.setEnabled(true);
            
            try {jVR.setText(LerValor.floatToCurrency(LerValor.StringToFloat(jOP.getText()),2));} catch (NullPointerException e) {}
            jVR.setEnabled(true); jVR.setEditable(false);
            jTR.setText("0,00"); jTR.setForeground(Color.black); 
            jTR.setVisible(false); jTRlabel.setVisible(false);
            
            jCH_banco.requestFocus();
            
            jbtLancar.setEnabled(false);
            this.tipo = 2;
        } else if (tipo == 3) {
            // Cartão
            jDN.setEnabled(false);
            jCH.setEnabled(false);
            jCT.setEnabled(true);
            
            jCT_numero.setText(null); jCT_numero.setEnabled(true);
            jCH_banco.setSelectedIndex(-1); jCH_banco.setEnabled(false);
            jCH_agencia.setText(null); jCH_agencia.setEnabled(false);
            jCH_numero.setText(null); jCH_numero.setEnabled(false);
            jCH_data.setDate(new Date()); jCH_data.setEnabled(false);
            
            try {jVR.setText(LerValor.floatToCurrency(LerValor.StringToFloat(jOP.getText()),2));} catch (NullPointerException e) {}
            jVR.setEnabled(true); jVR.setEditable(false);
            jTR.setText("0,00"); jTR.setForeground(Color.black); 
            jTR.setVisible(false); jTRlabel.setVisible(false);
            
            jCT_numero.requestFocus();
            
            jbtLancar.setEnabled(false);
            this.tipo = 3;
        }
    }
    
    public Object[] getPagRec() {
        return new Object[] {this.tipo, this.CT_numero, new Object[] {this.CH_banco, this.CH_agencia, this.CH_numero, this.CH_data}};
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jPagRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jPagRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jPagRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jPagRec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jPagRec dialog = new jPagRec(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCH;
    private javax.swing.JTextField jCH_agencia;
    private javax.swing.JComboBox jCH_banco;
    private com.toedter.calendar.JDateChooser jCH_data;
    private javax.swing.JTextField jCH_numero;
    private javax.swing.JLabel jCT;
    private javax.swing.JTextField jCT_numero;
    private javax.swing.JLabel jDN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField jOP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTR;
    private javax.swing.JLabel jTRlabel;
    private javax.swing.JFormattedTextField jVR;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtLancar;
    // End of variables declaration//GEN-END:variables
}
