/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cadastos;

import Db.DbMain;
import Funcoes.LerValor;
import Funcoes.VariaveisGlobais;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Samic
 */
public class CadTaxasConv extends javax.swing.JInternalFrame {
    DbMain conn = VariaveisGlobais.con;
    boolean bFill = false;
    boolean bAlt = false;

    boolean tpTaxa = false;
    String vrTaxaConsulta = "0,00";
    String vrTaxaProced = "0,00";
    String vrTxConMed = "0,00";
    String vrTxProMed = "0,00";
    
    /**
     * Creates new form CadTaxasConv
     */
    public CadTaxasConv() {
        initComponents();
        
        bFill = false;
        FillConvenios();
        bFill = true;
        
        SeekConv(cbxCodConv.getSelectedItem().toString());
    }

    private void FillConvenios() {
        String tsql = "select cv_numero, cv_apelido from convenios WHERE Upper(Trim(cv_apelido)) != 'PARTICULAR' ORDER BY Upper(Trim(cv_apelido));";
        ResultSet tbmedicos = conn.AbrirTabela(tsql, 1007);
        try {
            while (tbmedicos.next()) {
                String tcodigo = tbmedicos.getString("cv_numero");
                String tconvenio = tbmedicos.getString("cv_apelido").toUpperCase();

                cbxCodConv.addItem(tcodigo);
                cbxNomeConv.addItem(tconvenio);
            }
        } catch (Exception err) {err.printStackTrace();}
        DbMain.FecharTabela(tbmedicos);        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cbxCodConv = new javax.swing.JComboBox<>();
        cbxNomeConv = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        rbtValor = new javax.swing.JRadioButton();
        rbtPercent = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        tbxConsulta = new javax.swing.JTextField();
        txbProced = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txbConMed = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tbxProcMed = new javax.swing.JTextField();

        setBackground(new java.awt.Color(101, 227, 255));
        setTitle(".:: Cadastro de Taxas para Convênios");
        setOpaque(true);
        setVisible(true);

        jLabel1.setText("Convênio:");

        cbxCodConv.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCodConvItemStateChanged(evt);
            }
        });

        cbxNomeConv.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxNomeConvItemStateChanged(evt);
            }
        });

        jLabel2.setText("Nome:");

        rbtValor.setBackground(new java.awt.Color(101, 227, 255));
        buttonGroup1.add(rbtValor);
        rbtValor.setText("Valor");
        rbtValor.setEnabled(false);

        rbtPercent.setBackground(new java.awt.Color(101, 227, 255));
        buttonGroup1.add(rbtPercent);
        rbtPercent.setText("Percentual");
        rbtPercent.setEnabled(false);

        jLabel3.setText("Taxa de Consulta:");

        tbxConsulta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tbxConsulta.setText("0,00");
        tbxConsulta.setEnabled(false);

        txbProced.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txbProced.setText("0,00");
        txbProced.setEnabled(false);

        jLabel4.setText("Taxa de Proced:");

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/aguardando.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/ok.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.setEnabled(false);
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/atendendo.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel5.setText("Tx.Consulta Méd:");

        txbConMed.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txbConMed.setText("0,00");
        txbConMed.setEnabled(false);

        jLabel6.setText("Tx.Proced Méd:");

        tbxProcMed.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tbxProcMed.setText("0,00");
        tbxProcMed.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxCodConv, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxNomeConv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbxConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txbProced, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtValor)
                        .addGap(18, 18, 18)
                        .addComponent(rbtPercent)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txbConMed, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbxProcMed, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxCodConv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNomeConv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tbxConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txbProced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtValor)
                    .addComponent(rbtPercent)
                    .addComponent(jLabel5)
                    .addComponent(txbConMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tbxProcMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnGravar)
                    .addComponent(btnSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCodConvItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCodConvItemStateChanged
        if (bFill) {
            bFill = false;
            cbxNomeConv.setSelectedIndex(cbxCodConv.getSelectedIndex());
            bFill = true;
            SeekConv(cbxCodConv.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cbxCodConvItemStateChanged

    private void cbxNomeConvItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxNomeConvItemStateChanged
        if (bFill) {
            bFill = false;
            cbxCodConv.setSelectedIndex(cbxNomeConv.getSelectedIndex());
            bFill = true;
            SeekConv(cbxCodConv.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cbxNomeConvItemStateChanged

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        if (bAlt) {
            Object[] options = { "Sim", "Não" };
            int n = JOptionPane.showOptionDialog(this, "Deseja cancelar alteração deste convênio ?\n\nMUITO CUIDADO POIS TODOS OS DADOS LANÇADOS NESTE CONVENIO SERÃO PERDIDOS!!!", "Atenção", 0, 3, null, options, options[0]);
            if (n == 0) {
                rbtValor.setSelected(!tpTaxa);
                rbtValor.setEnabled(false);
                rbtPercent.setEnabled(false);
                tbxConsulta.setText(vrTaxaConsulta);
                tbxConsulta.setEnabled(false);                
                txbProced.setText(vrTaxaProced);
                txbProced.setEnabled(false);
                txbConMed.setText(vrTxConMed);
                txbConMed.setEnabled(false);
                tbxProcMed.setText(vrTxProMed);
                tbxProcMed.setEnabled(false);
                
                tpTaxa = false;
                vrTaxaConsulta = "0,00";
                vrTaxaProced = "0,00";
                vrTxConMed = "0,00";
                vrTxProMed = "0,00";
                
                cbxCodConv.requestFocus();
            }   
            bAlt = false;
            btnAlterar.setEnabled(true); btnGravar.setEnabled(false); btnSair.setEnabled(true);
            cbxCodConv.setEnabled(true); cbxNomeConv.setEnabled(true);
            cbxCodConv.requestFocus();
        } else {
            dispose();
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        tpTaxa = rbtValor.isSelected() ? false : true;
        rbtValor.setEnabled(true);
        vrTaxaConsulta = tbxConsulta.getText();
        tbxConsulta.setEnabled(true);                
        vrTaxaProced = txbProced.getText();
        txbProced.setEnabled(true);
        vrTxConMed = txbConMed.getText();
        txbConMed.setEnabled(true);
        vrTxProMed = txbProced.getText();
        tbxProcMed.setEnabled(true);
        
        cbxCodConv.setEnabled(false); cbxNomeConv.setEnabled(false);
        bAlt = true;
        btnAlterar.setEnabled(false); btnGravar.setEnabled(true); btnSair.setEnabled(true);
        rbtValor.requestFocus();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        if (bAlt) {
            Object[] options = { "Sim", "Não" };
            int n = JOptionPane.showOptionDialog(this, "Deseja gravar as alteração neste convênio ?", "Atenção", 0, 3, null, options, options[0]);
            if (n == 1) {
                rbtValor.setSelected(!tpTaxa);
                rbtValor.setEnabled(false);
                rbtPercent.setEnabled(false);
                tbxConsulta.setText(vrTaxaConsulta);
                tbxConsulta.setEnabled(false);                
                txbProced.setText(vrTaxaProced);
                txbProced.setEnabled(false);                
                txbConMed.setText(vrTxConMed);
                txbConMed.setEnabled(false);
                tbxProcMed.setText(vrTxProMed);
                tbxProcMed.setEnabled(false);

                tpTaxa = false;
                vrTaxaConsulta = "0,00";
                vrTaxaProced = "0,00";
                vrTxConMed = "0,00";
                vrTxProMed = "0,00";
            } else {
                String updateSQL = "update convenios set cv_tabelas = ?, cv_txconsulta = ?, cv_txproced = ?, cv_vrpconmed = ?, cv_vrppromed = ? where cv_numero = ?;";
                Object[][] param = new Object[][] {
                    {"string", (rbtValor.isSelected() ? "0" : "1")},
                    {"float", LerValor.StringToFloat(tbxConsulta.getText())},
                    {"float", LerValor.StringToFloat(txbProced.getText())},
                    {"float", LerValor.StringToFloat(txbConMed.getText())},
                    {"float", LerValor.StringToFloat(tbxProcMed.getText())},
                    {"int", Integer.valueOf(cbxCodConv.getSelectedItem().toString())}
                };
                conn.ExecutarComando(updateSQL, param);
                
                rbtValor.setEnabled(false);
                rbtPercent.setEnabled(false);
                tbxConsulta.setEnabled(false);                
                txbProced.setEnabled(false);
                txbConMed.setEnabled(false);                
                tbxProcMed.setEnabled(false);
                
                tpTaxa = false;
                vrTaxaConsulta = "0,00";
                vrTaxaProced = "0,00";
            }   
            bAlt = false;
            btnAlterar.setEnabled(true); btnGravar.setEnabled(false); btnSair.setEnabled(true);
            cbxCodConv.setEnabled(true); cbxNomeConv.setEnabled(true);
            cbxCodConv.requestFocus();
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void SeekConv(String codConv) {
        String tsql = "select cv_tabelas, cv_txconsulta, cv_txproced, cv_vrpconmed, cv_vrppromed from convenios WHERE cv_numero = '" + codConv + "' ORDER BY Upper(Trim(cv_apelido));";
        ResultSet tbmedicos = conn.AbrirTabela(tsql, ResultSet.CONCUR_READ_ONLY);
        try {
            while (tbmedicos.next()) {
                String tTipoVr = tbmedicos.getString("cv_tabelas");
                double tvrConsulta = tbmedicos.getDouble("cv_txconsulta");
                double tvrProced = tbmedicos.getDouble("cv_txproced");

                double tvrConMed = tbmedicos.getDouble("cv_vrpconmed");
                double tvrProMed = tbmedicos.getDouble("cv_vrppromed");

                try {
                    if (tTipoVr.equalsIgnoreCase("0")) rbtValor.setSelected(true); else rbtPercent.setSelected(true);
                } catch (Exception e) { rbtPercent.setSelected(true); }
                
                tbxConsulta.setText(LerValor.floatToCurrency((float)tvrConsulta,2));
                txbProced.setText(LerValor.floatToCurrency((float)tvrProced,2));
                
                txbConMed.setText(LerValor.floatToCurrency((float)tvrConMed,2));
                tbxProcMed.setText(LerValor.floatToCurrency((float)tvrProMed,2));
            }
        } catch (Exception err) {err.printStackTrace();}
        DbMain.FecharTabela(tbmedicos);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxCodConv;
    private javax.swing.JComboBox<String> cbxNomeConv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton rbtPercent;
    private javax.swing.JRadioButton rbtValor;
    private javax.swing.JTextField tbxConsulta;
    private javax.swing.JTextField tbxProcMed;
    private javax.swing.JTextField txbConMed;
    private javax.swing.JTextField txbProced;
    // End of variables declaration//GEN-END:variables
}
