/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cadastos;

import Db.DbMain;
import Funcoes.TableControl;
import Funcoes.VariaveisGlobais;
import java.awt.Point;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.PatternSyntaxException;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Samic
 */
public class jConvenios extends javax.swing.JInternalFrame {
    DbMain conn = VariaveisGlobais.con;
    String sql = "SELECT * FROM convenios ORDER BY cv_numero;";
    ResultSet urs = conn.AbrirTabela(sql, ResultSet.TYPE_SCROLL_INSENSITIVE);
    TableRowSorter<TableModel> sorter;

    /**
     * Creates new form nConvenios
     */
    public jConvenios() {
        initComponents();

        try { if (urs.first()) LerConvenios(); else LimpaTela(); } catch (SQLException e) {}           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mttxbValor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        mttxbValorMed = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btPesquisar = new javax.swing.JButton();
        btRetornar = new javax.swing.JButton();
        btGravar = new javax.swing.JButton();
        codConv = new javax.swing.JTextField();
        nmConv = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cvAns = new javax.swing.JTextField();
        cvTabela = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cvCodnoConv = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cvNumLote = new javax.swing.JTextField();

        setBackground(new java.awt.Color(101, 227, 255));
        setTitle(".:: Cadastro de Valor da Consulta");
        setOpaque(true);
        setVisible(true);

        jLabel10.setText("Convenio:");

        jLabel11.setText("Consulta:");

        mttxbValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mttxbValor.setText("0,00");

        jLabel12.setText("Valor Medico:");

        mttxbValorMed.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mttxbValorMed.setText("0,00");

        jPanel1.setBackground(new java.awt.Color(101, 227, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        btRetornar.setText("Retornar");
        btRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetornarActionPerformed(evt);
            }
        });

        btGravar.setText("Gravar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(btGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRetornar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPesquisar)
                    .addComponent(btRetornar)
                    .addComponent(btGravar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        codConv.setEditable(false);
        codConv.setBackground(new java.awt.Color(255, 255, 255));

        nmConv.setEditable(false);
        nmConv.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setText("Tabela:");

        jLabel14.setText("ANS:");

        jLabel15.setText("Cd.naConv:");

        jLabel16.setText("NºLote:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cvAns, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cvTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cvCodnoConv, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 5, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codConv, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nmConv, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cvNumLote)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mttxbValor, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mttxbValorMed, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(codConv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nmConv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(cvAns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cvTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(cvCodnoConv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(mttxbValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(mttxbValorMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(cvNumLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        String tsql = "SELECT cv_numero, cv_convenio, cv_apelido FROM convenios ORDER BY Lower(cv_convenio);";
        ResultSet trs = conn.AbrirTabela(tsql, ResultSet.CONCUR_READ_ONLY);
        final JTable tbl = new JTable();
        tbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent me) {
                JTable table =(JTable) me.getSource();
                Point p = me.getPoint();
                int row = table.rowAtPoint(p);
                if (me.getClickCount() == 2) {
                    int trow = tbl.getSelectedRow();
                    int modelRow = tbl.convertRowIndexToModel(trow);
                    String tficha = tbl.getModel().getValueAt(modelRow, 0).toString();
                    BuscarConvenio(tficha);
                }
            }
        });

        String[][] aheader = { { "codigo", "nome", "apelido" }, { "60", "380", "150" } };
        TableControl.header(tbl, aheader);
        TableControl.delall(tbl);

        String mcod = null, mnome = null, mfuncao = null;
        try {
            while (trs.next()) {
                try { mcod = trs.getString("cv_numero"); } catch (SQLException e) {}
                try { mnome = trs.getString("cv_convenio"); } catch (SQLException e) {}
                try { mfuncao = trs.getString("cv_apelido"); } catch (SQLException e) {}
                TableControl.add(tbl, new String[][] { { mcod, mnome, mfuncao }, { "C", "L", "L" } }, true);
                sorter = new TableRowSorter(tbl.getModel());
                tbl.setRowSorter(sorter);
            }
        } catch (SQLException e) {}
        try {trs.close();} catch (SQLException e) {}
        tbl.setSize(300,200);

        JScrollPane jScrollPane1 = new JScrollPane();
        jScrollPane1.setViewportView(tbl);
        JLabel jLabel1 = new JLabel();
        jLabel1.setText("Buscar:");
        final JTextField jbuscar = new JTextField();
        jbuscar.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                if ("".equals(jbuscar.getText().trim())) {
                    sorter.setRowFilter(null);
                } else {
                    try {
                        sorter.setRowFilter(
                            RowFilter.regexFilter(jbuscar.getText().trim()));
                    } catch (PatternSyntaxException pse) {
                        System.err.println("Bad regex pattern");
                    }
                }
            }

            public void keyTyped(KeyEvent e) {
            }

            public void keyPressed(KeyEvent e) {
            }
        });
        jbuscar.requestFocus();

        JPanel panel = new JPanel();
        GroupLayout layout = new GroupLayout(panel);
        //getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 275, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jbuscar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel.setLayout(layout);
        Object[] options = { "Ok", "Cancelar" };
        int opc = JOptionPane.showOptionDialog(this, panel,"Selecione o convenio!",JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null,options, options[0]);
        if (opc == JOptionPane.YES_OPTION) {
            int trow = tbl.getSelectedRow();
            int modelRow = tbl.convertRowIndexToModel(trow);
            String tficha = tbl.getModel().getValueAt(modelRow, 0).toString();
            BuscarConvenio(tficha);
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetornarActionPerformed
            dispose();
    }//GEN-LAST:event_btRetornarActionPerformed

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        String tsql = "UPDATE convenios SET cv_ans = ?, cv_codtabelas = ?, " +
            "cv_codoperadora = ?, cv_numerador = ?, cv_consultavr = ?, cv_medicovr = ? WHERE cv_numero = ?;";
        Object[][] param = new Object[][] {
                {"string",cvAns.getText()},
                {"string",cvTabela.getText()},
                {"string", cvCodnoConv.getText()},
                {"int", Integer.parseInt(cvNumLote.getText().trim())},
                {"decimal", new BigDecimal(mttxbValor.getText().replace(".", "").replace(",", "."))},
                {"decimal", new BigDecimal(mttxbValorMed.getText().replace(".", "").replace(",", "."))},
                {"int",Integer.valueOf(codConv.getText())}
            };
        try { conn.ExecutarComando(tsql, param); } catch (Exception e) {}
    }//GEN-LAST:event_btGravarActionPerformed

    private void BuscarConvenio(String cvcodigo) {
        try {urs.first();} catch (SQLException e) {}
        try {
            while (urs.next()) {
                if (urs.getString("cv_numero").equalsIgnoreCase(cvcodigo)) {
                    LerConvenios();
                    break;
                }
            }
        } catch (SQLException e) {}
    }

    private void LimpaTela() {
        codConv.setText("");
        nmConv.setText("");
        cvAns.setText("");
        cvTabela.setText("");
        cvCodnoConv.setText("");
        cvNumLote.setText("0");
        mttxbValor.setText("0,00");
        mttxbValorMed.setText("0,00");
    }
    
    private void LerConvenios() {
        try { codConv.setText(urs.getString("cv_numero")); } catch (SQLException e) { codConv.setText("0"); }
        try { nmConv.setText(urs.getString("cv_convenio")); } catch (SQLException e) { nmConv.setText(""); }
        try { cvAns.setText(urs.getString("cv_ans")); } catch (SQLException e) { cvAns.setText(""); }
        try { cvTabela.setText(urs.getString("cv_codtabelas")); } catch (SQLException e) { cvTabela.setText(""); }
        try { cvCodnoConv.setText(urs.getString("cv_codoperadora")); } catch (SQLException e) { cvCodnoConv.setText(""); }
        try { cvNumLote.setText(String.valueOf(urs.getInt("cv_numerador"))); } catch (SQLException e) { cvNumLote.setText(""); }
        try { mttxbValor.setText(urs.getBigDecimal("cv_consultavr").toPlainString().toString().replace(".", ",")); } catch (SQLException e) { mttxbValor.setText("0,00"); }
        try { mttxbValorMed.setText(urs.getBigDecimal("cv_medicovr").toPlainString().toString().replace(".", ",")); } catch (SQLException e) { mttxbValorMed.setText("0,00"); }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btRetornar;
    private javax.swing.JTextField codConv;
    private javax.swing.JTextField cvAns;
    private javax.swing.JTextField cvCodnoConv;
    private javax.swing.JTextField cvNumLote;
    private javax.swing.JTextField cvTabela;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mttxbValor;
    private javax.swing.JTextField mttxbValorMed;
    private javax.swing.JTextField nmConv;
    // End of variables declaration//GEN-END:variables
}
