/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Faturamentos;

import Db.DbMain;
import Funcoes.TableControl;
import Funcoes.VariaveisGlobais;
import static java.lang.Thread.sleep;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Samic
 */
public class jGrupoBusca extends javax.swing.JDialog {
    DbMain conn = VariaveisGlobais.con;
    TableRowSorter<TableModel> sorterGrupos;
    int tam = 0, n = 0;
    String retorno = null;

    /**
     * Creates new form jGrupoBusca
     */
    public jGrupoBusca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // Grupos
        String[][] gcheader = {{"Codigo","Descrição"}, {"80","600"}};
        TableControl.header(Grupos, gcheader, new boolean[] {false, false});
        FillGrupos();
    }

    private void FillGrupos() {
        // limpa controle
        TableControl.Clear(Grupos);
        
        // Bloqueia
        Grupos.setEnabled(false);
        
        gBuscar.setEnabled(false);
        
        String sql = "SELECT id, descricao FROM grupos ORDER BY UPPER(TRIM(descricao));";
        ResultSet rs = conn.AbrirTabela(sql, ResultSet.CONCUR_READ_ONLY);
        try {
            tam = conn.RecordCount(rs);
            n = 1;
            pbGrupos.setValue(0);
            pbGrupos.setVisible(true);

            while (rs.next()) {                
                new Thread() {
                    public void run() {
                        int pos = (n * 100) / tam;
                        try {sleep(100);} catch (Exception ex) {}
                        
                        pbGrupos.setValue(pos);
                        pbGrupos.repaint();
                    }
                }.start();                

                String tcodigo = rs.getString("id");
                String tdescri = rs.getString("descricao").toUpperCase();
                
                TableControl.add(Grupos, new String[][] {{tcodigo, tdescri}, { "C", "L" } }, true);
                n++;
            }
        } catch (Exception e) {}
        DbMain.FecharTabela(rs);
        
        sorterGrupos = null;
        sorterGrupos = new TableRowSorter<TableModel>(Grupos.getModel());
        Grupos.setRowSorter(sorterGrupos);

        pbGrupos.setValue(1);
        pbGrupos.repaint();

        // Desbloqueia
        Grupos.setEnabled(true);
        gBuscar.setEnabled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pbGrupos = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        Grupos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        gBuscar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnConfirma = new javax.swing.JButton();
        lblGrupos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".:: Busca de Grupos de Medicamentos");
        setBackground(new java.awt.Color(101, 227, 255));
        setModal(true);
        setResizable(false);

        Grupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Grupos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        Grupos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Grupos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Grupos);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Buscar:");

        gBuscar.setBorder(null);
        gBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gBuscarKeyReleased(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/clear.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(gBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2))
        );

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnConfirma.setText("Confirma");
        btnConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmaActionPerformed(evt);
            }
        });

        lblGrupos.setBackground(new java.awt.Color(153, 204, 255));
        lblGrupos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGrupos.setForeground(new java.awt.Color(0, 0, 204));
        lblGrupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Figuras/aguardando.png"))); // NOI18N
        lblGrupos.setText(".:: Grupos");
        lblGrupos.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirma)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGrupos)
                    .addComponent(pbGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCadastrar)
                        .addComponent(btnConfirma)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gBuscarKeyReleased
        try {
            if ("".equals(gBuscar.getText().trim())) {
                sorterGrupos.setRowFilter(null);
            } else {
                if (gBuscar.getText() != null) sorterGrupos.setRowFilter(RowFilter.regexFilter(gBuscar.getText().trim(), new int[0]));
            }
        } catch (Exception pse) {
            //System.err.println("Bad regex pattern");
        }
    }//GEN-LAST:event_gBuscarKeyReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        gBuscar.setText("");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (gBuscar.getText().trim().equalsIgnoreCase("")) return;
        if (Grupos.getSelectedRow() != -1) {
            JOptionPane.showMessageDialog(null, "Não pode adicionar um item existente!","Atenção",INFORMATION_MESSAGE);
            return;
        }

        String insertSQL = "INSERT INTO grupos (descricao) VALUES ('" + gBuscar.getText().trim() + "');";
        if (conn.ExecutarComando(insertSQL) != 0) {
            String tcodigo = BuscaNewId(gBuscar.getText().trim());
            if (tcodigo != null) {
                TableControl.add(Grupos, new String[][] {{tcodigo, gBuscar.getText().trim()}, { "C", "L" } }, true);

                sorterGrupos = null;
                sorterGrupos = new TableRowSorter<TableModel>(Grupos.getModel());
                Grupos.setRowSorter(sorterGrupos);

                JOptionPane.showMessageDialog(null, "Item adicionado!","Atenção",INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao adicionar!","Atenção",INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao adicionar!","Atenção",INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaActionPerformed
        if (Grupos.getSelectedRow() == -1) return;
        this.retorno = Grupos.getValueAt(Grupos.getSelectedRow(),0).toString();
        dispose();
    }//GEN-LAST:event_btnConfirmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jGrupoBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jGrupoBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jGrupoBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jGrupoBusca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jGrupoBusca dialog = new jGrupoBusca(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private String BuscaNewId(String value) {
        String retorno = null;
        String sql = "SELECT id, descricao FROM grupos WHERE Upper(Trim(descricao)) = '" + value.toUpperCase() + "'ORDER BY UPPER(TRIM(descricao));";
        ResultSet rs = conn.AbrirTabela(sql, ResultSet.CONCUR_READ_ONLY);
        try {
            while (rs.next()) {                
                retorno = rs.getString("id");
            }
        } catch (Exception ex) {}
        DbMain.FecharTabela(rs);
        return retorno;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Grupos;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnConfirma;
    private javax.swing.JTextField gBuscar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblGrupos;
    private javax.swing.JProgressBar pbGrupos;
    // End of variables declaration//GEN-END:variables
}
