/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Relatorios;

import Db.DbMain;
import Funcoes.Dates;
import Funcoes.FuncoesGlobais;
import Funcoes.VariaveisGlobais;
import java.sql.ResultSet;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JComboBox;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author supervisor
 */
public class iRelEstatisticas extends javax.swing.JInternalFrame {
    DbMain conn = VariaveisGlobais.con;

    /**
     * Creates new form iRelEstatisticas
     */
    public iRelEstatisticas() {
        initComponents();
        
        FaixaEtaria();
    }

    private void FillIndicados(JComboBox table) {
        String tsql = "select DISTINCT UPPER(ma_indicado) AS INDICACAO from faturar where trim(ma_indicado) <> '' ORDER BY UPPER(ma_indicado);";
        ResultSet tbmedicos = conn.AbrirTabela(tsql, ResultSet.CONCUR_READ_ONLY);
        table.removeAllItems();
        try {
            while (tbmedicos.next()) {                
                String tindica = tbmedicos.getString("INDICACAO");
                
                table.addItem(tindica);
            }
        } catch (Exception err) {}
        DbMain.FecharTabela(tbmedicos);
    }
    
    private void FillMedicos(JComboBox table) {
        String tsql = "select m.md_codigo, m.md_categoria, f.usuario, m.md_nome, m.md_codigo from medicos as m, cadfun as f where m.md_cpf = f.f_cpf order by m.md_nome;";
        ResultSet tbmedicos = conn.AbrirTabela(tsql, ResultSet.CONCUR_READ_ONLY);
        table.removeAllItems();
        try {
            while (tbmedicos.next()) {                
                String tindica = tbmedicos.getString("md_nome");
                
                table.addItem(tindica);
            }
        } catch (Exception err) {}
        DbMain.FecharTabela(tbmedicos);
    }

    private void FaixaEtaria() {
        fe_maior.setText("Maior de " + fe_idade.getText() + " anos");
        fe_menor.setText("Menor, igual de " + fe_idade.getText() + " anos");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getario = new javax.swing.ButtonGroup();
        ggenero = new javax.swing.ButtonGroup();
        grenda = new javax.swing.ButtonGroup();
        gfiltro = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        fe_menor = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        fe_idade = new javax.swing.JFormattedTextField();
        fe_maior = new javax.swing.JRadioButton();
        fe_ambos = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        ge_masculino = new javax.swing.JRadioButton();
        ge_feminino = new javax.swing.JRadioButton();
        ge_ambos = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        rd_familiar = new javax.swing.JRadioButton();
        rd_percapta = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rd_vrinicial = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        rd_vrfinal = new javax.swing.JFormattedTextField();
        rd_pessoal = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pe_dtinic = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        pe_dtfinal = new javax.swing.JFormattedTextField();
        btGerar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();

        setBackground(new java.awt.Color(101, 227, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle(".:: Relatório");
        setMaximumSize(null);
        setMinimumSize(null);
        setOpaque(true);
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(101, 227, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("[ Faixa Etária ]"));
        jPanel1.setMaximumSize(new java.awt.Dimension(174, 169));
        jPanel1.setMinimumSize(new java.awt.Dimension(174, 169));

        fe_menor.setBackground(new java.awt.Color(101, 227, 255));
        getario.add(fe_menor);
        fe_menor.setText("Menor de XX anos");

        jLabel4.setText("Menoridade:");

        fe_idade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("00"))));
        fe_idade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fe_idade.setText("18");
        fe_idade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fe_idadeKeyReleased(evt);
            }
        });

        fe_maior.setBackground(new java.awt.Color(101, 227, 255));
        getario.add(fe_maior);
        fe_maior.setText("Maior de XX anos");

        fe_ambos.setBackground(new java.awt.Color(101, 227, 255));
        getario.add(fe_ambos);
        fe_ambos.setSelected(true);
        fe_ambos.setText("Ambos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(15, 15, 15)
                        .addComponent(fe_idade, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fe_menor)
                    .addComponent(fe_ambos)
                    .addComponent(fe_maior))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fe_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(fe_menor)
                .addGap(18, 18, 18)
                .addComponent(fe_maior)
                .addGap(18, 18, 18)
                .addComponent(fe_ambos)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(101, 227, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("[ Gênero ]"));
        jPanel2.setMaximumSize(new java.awt.Dimension(161, 144));
        jPanel2.setMinimumSize(new java.awt.Dimension(161, 144));

        ge_masculino.setBackground(new java.awt.Color(101, 227, 255));
        ggenero.add(ge_masculino);
        ge_masculino.setText("Masculino");

        ge_feminino.setBackground(new java.awt.Color(101, 227, 255));
        ggenero.add(ge_feminino);
        ge_feminino.setText("Feminino");

        ge_ambos.setBackground(new java.awt.Color(101, 227, 255));
        ggenero.add(ge_ambos);
        ge_ambos.setSelected(true);
        ge_ambos.setText("Ambos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ge_masculino)
                    .addComponent(ge_feminino)
                    .addComponent(ge_ambos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ge_masculino)
                .addGap(29, 29, 29)
                .addComponent(ge_feminino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(ge_ambos)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(101, 227, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("[ Rendas ]"));
        jPanel3.setMaximumSize(new java.awt.Dimension(250, 171));
        jPanel3.setMinimumSize(new java.awt.Dimension(250, 171));
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 171));

        rd_familiar.setBackground(new java.awt.Color(101, 227, 255));
        grenda.add(rd_familiar);
        rd_familiar.setText("Familiar");

        rd_percapta.setBackground(new java.awt.Color(101, 227, 255));
        grenda.add(rd_percapta);
        rd_percapta.setText("Per Cápta");

        jLabel5.setText("Faixas:");

        rd_vrinicial.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        rd_vrinicial.setText("0,00");

        jLabel6.setText("até");

        rd_vrfinal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        rd_vrfinal.setText("0,00");

        rd_pessoal.setBackground(new java.awt.Color(101, 227, 255));
        grenda.add(rd_pessoal);
        rd_pessoal.setSelected(true);
        rd_pessoal.setText("Pessoal");

        jLabel7.setText("de");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rd_percapta)
                    .addComponent(rd_familiar)
                    .addComponent(jLabel5)
                    .addComponent(rd_pessoal)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(32, 32, 32)
                        .addComponent(rd_vrfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rd_vrinicial, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(rd_pessoal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd_familiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd_percapta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd_vrinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rd_vrfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(101, 227, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("[ Período ]"));
        jPanel5.setMaximumSize(new java.awt.Dimension(597, 72));
        jPanel5.setMinimumSize(new java.awt.Dimension(597, 72));

        jLabel1.setText("De:");

        try {
            pe_dtinic.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setText("até");

        try {
            pe_dtfinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(pe_dtinic, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addComponent(pe_dtfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pe_dtinic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pe_dtfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btGerar.setText("Gerar Relatório");
        btGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarActionPerformed(evt);
            }
        });

        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btGerar)
                        .addGap(6, 6, 6)
                        .addComponent(btFechar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGerar)
                    .addComponent(btFechar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    private void fe_idadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fe_idadeKeyReleased
        FaixaEtaria();
    }//GEN-LAST:event_fe_idadeKeyReleased

    private void btGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarActionPerformed
        String fSexo = "";
        if (ge_masculino.isSelected()) { 
            fSexo = "AND (SubString(Upper(p.pc_sexo),1,1) = 'M') " ; 
        } else if (ge_feminino.isSelected()) { 
            fSexo = "AND (SubString(Upper(p.pc_sexo),1,1) = 'F') " ; 
        } else {
            fSexo = ""; 
        }
        String fIdade = "";
        if (fe_menor.isSelected()) {
            fIdade = "AND (age(p.pc_nascimento) <= (interval '" + fe_idade.getText() + " year')) ";
        } else if (fe_maior.isSelected()) {
            fIdade = "AND (age(p.pc_nascimento) > (interval '" + fe_idade.getText() + " year')) ";
        } else {
            fIdade = "";
        }
        String fRenda = ""; String fVar = "";
        if (rd_pessoal.isSelected()) {
            fRenda = "AND (&1. >= &2. AND &1. <= &3.)";
            fVar = "p.pc_renda";
            fRenda = FuncoesGlobais.Subst(fRenda, new String[] {fVar, rd_vrinicial.getText().replace(",", "."), rd_vrfinal.getText().replace(",", ".")});
        } else if (rd_familiar.isSelected())  {
            fRenda = "AND (&1. >= &2. AND &1. <= &3.)";
            fVar = "p.pc_rendafam";
            fRenda = FuncoesGlobais.Subst(fRenda, new String[] {fVar, rd_vrinicial.getText().replace(",", "."), rd_vrfinal.getText().replace(",", ".")});
        } else {
            fRenda = "AND (&1. >= &2. AND &1. <= &3.)";
            fVar = "p.pc_rendaper";
            fRenda = FuncoesGlobais.Subst(fRenda, new String[] {fVar, rd_vrinicial.getText().replace(",", "."), rd_vrfinal.getText().replace(",", ".")});
        }
        String query = "SELECT f.ma_data, Upper(p.pc_nome) AS paciente, p.pc_nascimento, " + 
                       "(select extract(year from age(p.pc_nascimento))) as idade, " + 
                       "SubString(Upper(p.pc_sexo),1,1) AS sexo, p.pc_renda, p.pc_rendafam, " + 
                       "p.pc_pessoas, p.pc_rendaper, Upper(f.ma_indicado) AS indicacao, " + 
                       "Upper(f.ma_medico) AS medico, f.ma_codmedico FROM faturar f, pacientes p " + 
                       "WHERE (f.ma_pcnumero = p.pc_numero) AND " + 
                       "(f.ma_data >= '" + Dates.StringtoString(pe_dtinic.getText(),"dd-MM-yyyy", "yyyy-MM-dd") + 
                       "' AND f.ma_data <= '" + Dates.StringtoString(pe_dtfinal.getText(),"dd-MM-yyyy", "yyyy-MM-dd") + "') " + 
                       fSexo +  
                       fIdade + 
                       fRenda + 
                       " ORDER BY f.ma_data, f.ma_codmedico, p.pc_nome;";
        ResultSet rs = conn.AbrirTabela(query, ResultSet.CONCUR_READ_ONLY);

        //implementação da interface JRDataSource para DataSource ResultSet
        JRResultSetDataSource jrRS = new JRResultSetDataSource( rs );

        String outFileName = "./reports/Relatorios/est1_0_" + Dates.DateFormat("ddMMyyyy", new Date()) + ".pdf";
        String fileName = "./reports/rEst1_0.jasper";

        //executa o relatório
        Map parametros = new HashMap();
        parametros.put("parameter1", "");

        try {
            JasperPrint print = JasperFillManager.fillReport(fileName, null, jrRS);
//            if (!"jasper".equals(VariaveisGlobais.reader)) {
//                ComandoExterno ce = new ComandoExterno();
//                ComandoExterno.ComandoExterno(VariaveisGlobais.reader + " " + outFileName);
//            } else {
                JasperViewer viewer = new JasperViewer(print, false);
                viewer.show();
//            }

        } catch (Exception ex) {ex.printStackTrace();}
        DbMain.FecharTabela(rs);
        
    }//GEN-LAST:event_btGerarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btGerar;
    private javax.swing.JRadioButton fe_ambos;
    private javax.swing.JFormattedTextField fe_idade;
    private javax.swing.JRadioButton fe_maior;
    private javax.swing.JRadioButton fe_menor;
    private javax.swing.JRadioButton ge_ambos;
    private javax.swing.JRadioButton ge_feminino;
    private javax.swing.JRadioButton ge_masculino;
    private javax.swing.ButtonGroup getario;
    private javax.swing.ButtonGroup gfiltro;
    private javax.swing.ButtonGroup ggenero;
    private javax.swing.ButtonGroup grenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JFormattedTextField pe_dtfinal;
    private javax.swing.JFormattedTextField pe_dtinic;
    private javax.swing.JRadioButton rd_familiar;
    private javax.swing.JRadioButton rd_percapta;
    private javax.swing.JRadioButton rd_pessoal;
    private javax.swing.JFormattedTextField rd_vrfinal;
    private javax.swing.JFormattedTextField rd_vrinicial;
    // End of variables declaration//GEN-END:variables
}
