/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Atendimentos;

import Db.DbMain;
import Funcoes.Dates;
import Funcoes.VariaveisGlobais;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Samic
 */
public class jQuestionario extends javax.swing.JDialog {
    DbMain conn = VariaveisGlobais.con;
    String cdPac;
    
    /**
     * Creates new form jQuestionario
     */
    public jQuestionario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
    }

    public void setCdPac(String value) { this.cdPac = value; }
    
    public void LerQuestionario() {
        ResultSet rs = conn.AbrirTabela("SELECT pc_escsimnao, pc_bensimnao, pc_benqual, pc_trabsimnao, pc_trabformsimnao, pc_drogsimnao, pc_drogqual FROM pacientes WHERE pc_numero = Cast('" + this.cdPac + "' AS double precision);", ResultSet.CONCUR_READ_ONLY);
        try {
            while (rs.next()) {
                if (rs.getBoolean("pc_escsimnao")) {
                    escSim.setSelected(true);
                } else escNao.setSelected(true);
                if (rs.getBoolean("pc_bensimnao")) {
                    benefSim.setSelected(true);
                    benefQual.setText(rs.getString("pc_benqual"));
                } else {
                    benefNao.setSelected(true);
                    benefQual.setText("");
                }
                if (rs.getBoolean("pc_trabsimnao")) {
                    trabSim.setSelected(true);
                } else trabNao.setSelected(true);
                if (rs.getBoolean("pc_trabformsimnao")) {
                    formSim.setSelected(true);
                } else formNao.setSelected(true);
                if (rs.getBoolean("pc_drogsimnao")) {
                    drogSim.setSelected(true);
                    drogQual.setText(rs.getString("pc_drogqual"));
                } else {
                    drogNao.setSelected(true);
                    drogQual.setText("");
                }                
            }
        } catch (Exception e) {e.printStackTrace();}
        DbMain.FecharTabela(rs);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        grupoEscola = new javax.swing.ButtonGroup();
        grupoBeneficio = new javax.swing.ButtonGroup();
        grupoTrabalho = new javax.swing.ButtonGroup();
        grupoFormal = new javax.swing.ButtonGroup();
        grupoDrogas = new javax.swing.ButtonGroup();
        jLabel33 = new javax.swing.JLabel();
        escSim = new javax.swing.JRadioButton();
        escNao = new javax.swing.JRadioButton();
        formNao = new javax.swing.JRadioButton();
        benefNao = new javax.swing.JRadioButton();
        jLabel40 = new javax.swing.JLabel();
        benefSim = new javax.swing.JRadioButton();
        drogSim = new javax.swing.JRadioButton();
        jLabel36 = new javax.swing.JLabel();
        drogNao = new javax.swing.JRadioButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        benefQual = new javax.swing.JTextField();
        drogQual = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        trabSim = new javax.swing.JRadioButton();
        trabNao = new javax.swing.JRadioButton();
        jLabel39 = new javax.swing.JLabel();
        formSim = new javax.swing.JRadioButton();
        btnGravar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".:: Questionário");
        setModal(true);
        setResizable(false);

        jLabel33.setText("1 - Frequenta a Escola?");

        grupoEscola.add(escSim);
        escSim.setText("Sim");

        grupoEscola.add(escNao);
        escNao.setText("Não");

        grupoFormal.add(formNao);
        formNao.setText("Não");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, trabSim, org.jdesktop.beansbinding.ELProperty.create("${selected}"), formNao, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        grupoBeneficio.add(benefNao);
        benefNao.setText("Não");
        benefNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                benefNaoActionPerformed(evt);
            }
        });

        jLabel40.setText("4 -Já fez uso de alguma substância lícita ou ilícita?   Entendendo  que seja qualquer tipo de droga lícita ou ilícita (cigarro, álcool, maconha, cocaína, crack e outras)");

        grupoBeneficio.add(benefSim);
        benefSim.setText("Sim");
        benefSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                benefSimActionPerformed(evt);
            }
        });

        grupoDrogas.add(drogSim);
        drogSim.setText("Sim");
        drogSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drogSimActionPerformed(evt);
            }
        });

        jLabel36.setText("2 - Recebe algum benefício?   Entendendo que seja qualquer benefício: PBF, BPC, aposentadoria, auxilio para idosos da Caixa e auxilio para bolsa da Caixa");

        grupoDrogas.add(drogNao);
        drogNao.setText("Não");
        drogNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drogNaoActionPerformed(evt);
            }
        });

        jLabel37.setText("Qual:");

        jLabel41.setText("Qual:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, benefSim, org.jdesktop.beansbinding.ELProperty.create("${selected}"), benefQual, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, drogSim, org.jdesktop.beansbinding.ELProperty.create("${selected}"), drogQual, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jLabel38.setText("3 - Trabalha?");

        grupoTrabalho.add(trabSim);
        trabSim.setText("Sim");

        grupoTrabalho.add(trabNao);
        trabNao.setText("Não");

        jLabel39.setText("Formal?");

        grupoFormal.add(formSim);
        formSim.setText("Sim");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, trabSim, org.jdesktop.beansbinding.ELProperty.create("${selected}"), formSim, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel33)
                        .addComponent(jLabel36)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(escSim)
                                    .addGap(18, 18, 18)
                                    .addComponent(escNao))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(benefSim)
                                    .addGap(18, 18, 18)
                                    .addComponent(benefNao)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel37)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(benefQual)))))
                    .addComponent(jLabel38)
                    .addComponent(jLabel40)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(formSim)
                                .addGap(18, 18, 18)
                                .addComponent(formNao))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(trabSim)
                                .addGap(18, 18, 18)
                                .addComponent(trabNao))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(drogSim)
                                .addGap(18, 18, 18)
                                .addComponent(drogNao)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(drogQual, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(escSim)
                    .addComponent(escNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(benefSim)
                    .addComponent(benefNao)
                    .addComponent(jLabel37)
                    .addComponent(benefQual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trabSim)
                    .addComponent(trabNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formSim)
                    .addComponent(formNao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drogSim)
                    .addComponent(drogNao)
                    .addComponent(jLabel41)
                    .addComponent(drogQual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGravar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void benefSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_benefSimActionPerformed
        if (benefSim.isSelected()) benefQual.requestFocus();
    }//GEN-LAST:event_benefSimActionPerformed

    private void drogSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drogSimActionPerformed
        if (drogSim.isSelected()) drogQual.requestFocus();
    }//GEN-LAST:event_drogSimActionPerformed

    private void benefNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_benefNaoActionPerformed
        if (benefNao.isSelected()) benefQual.setText("");
    }//GEN-LAST:event_benefNaoActionPerformed

    private void drogNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drogNaoActionPerformed
        if (drogNao.isSelected()) drogQual.setText("");
    }//GEN-LAST:event_drogNaoActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
      String sql = "UPDATE pacientes SET pc_escsimnao=?, pc_bensimnao=?, pc_benqual=?, pc_trabsimnao=?, pc_trabformsimnao=?, pc_drogsimnao=?, pc_drogqual=? WHERE pc_numero=?;";
      try {
        PreparedStatement stm = conn.conn.prepareStatement(sql);
        stm.setBoolean(1, escSim.isSelected());
        stm.setBoolean(2, benefSim.isSelected());
        stm.setString(3, benefQual.getText());
        stm.setBoolean(4, trabSim.isSelected());
        stm.setBoolean(5, formSim.isSelected());
        stm.setBoolean(6, drogSim.isSelected());
        stm.setString(7, drogQual.getText());
        stm.setDouble(8, Double.valueOf(this.cdPac));
        stm.execute();
        stm.close();
      } catch (SQLException e) {e.printStackTrace();}
      dispose();
    }//GEN-LAST:event_btnGravarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jQuestionario dialog = new jQuestionario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton benefNao;
    private javax.swing.JTextField benefQual;
    private javax.swing.JRadioButton benefSim;
    private javax.swing.JButton btnGravar;
    private javax.swing.JRadioButton drogNao;
    private javax.swing.JTextField drogQual;
    private javax.swing.JRadioButton drogSim;
    private javax.swing.JRadioButton escNao;
    private javax.swing.JRadioButton escSim;
    private javax.swing.JRadioButton formNao;
    private javax.swing.JRadioButton formSim;
    private javax.swing.ButtonGroup grupoBeneficio;
    private javax.swing.ButtonGroup grupoDrogas;
    private javax.swing.ButtonGroup grupoEscola;
    private javax.swing.ButtonGroup grupoFormal;
    private javax.swing.ButtonGroup grupoTrabalho;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JRadioButton trabNao;
    private javax.swing.JRadioButton trabSim;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
